[정렬, 맵, 셋] 2월 20일
Altu-Bitu-6/Altu-Bitu-OhSeoyoung pull request #1
Opened 2024-02-20 08:23 UTC by SeoyoungOhMe

### 인적사항
학번 : 2171070
이름 : 오서영
</br>

### 과제제출
기존 제출 : 없음
추가 제출 : 1431, 14425, 19636
</br>

2024-02-21 16:01 UTC, kimhj010502 requested changes
정렬, 맵, 셋 구현 문제 19636번 코드에 오류가 있어 제출로 인정되지 않아요. 확인 부탁드립니다~!

2024-02-23 08:41 UTC, kimhj010502 approved these changes
**[정렬, 맵, 셋 구현 문제 코드 리뷰 완료]**

서영님 안녕하세요!
과제하시느라 수고 많으셨습니다!!
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-02-23 08:41 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +};
구조체 선언한 거 좋아요~👍

2024-02-23 08:41 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +}
복잡한 연산 과정을 잘 구현해주셨네요! 함수 분리도 좋아요

2024-02-23 08:41 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +    }
이런 과정도 함수로 따로 정의하면 더 좋을 것 같아요~

2024-02-23 11:41 UTC, chae-jpg approved these changes
**[정렬, 맵, 셋 이론 코드리뷰 완료]**

1431(P3), 14425(P3)
서영님 안녕하세요! 코드 리뷰 완료되었습니다👍
주석 처리 좋았고, 문제도 깔끔하게 잘 풀어주셨어요!
몇 가지 사소한 코멘트 남겼습니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-02-23 11:41 UTC, chae-jpg commented on 01_정렬_맵_셋/1431.cpp
> +bool cmp(const string& s1, const string& s2) {
사용자 정의 정렬을 위해서 비교 함수를 잘 선언해주셨네요!

2024-02-23 11:41 UTC, chae-jpg commented on 01_정렬_맵_셋/1431.cpp
> +        if (s1[i] > 47 && s1[i] < 58) {
47, 58 보다 '0', '9' 로 표현하면 가독성이 더 좋아질 것 같아요!

2024-02-23 11:41 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +	}
빠른 속도로 탐색이 가능한 셋을 잘 사용해서 문제를 깔끔하게 풀어주셨네요!👍

2024-04-08 13:53 UTC, merged